sudo: required
services:
  - docker

before_install:
  - docker build -t josephbeerman/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true josephbeerman/react-test npm test

after_success:
  - docker build -t josephbeerman/multi-client ./client
  - docker build -t josephbeerman/multi-nginx ./nginx
  - docker build -t josephbeerman/multi-server ./server
  - docker build -t josephbeerman/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push josephbeerman/multi-client
  - docker push josephbeerman/multi-nginx
  - docker push josephbeerman/multi-server
  - docker push josephbeerman/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'eu-west-2'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-eu-west-2-648730480972'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY